/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AMenu: typeof import('antdv-next')['Menu']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
  }
}
